name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./auth_service
          file: ./auth_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest

      - name: Copy Stack File to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-stack.yml"
          target: "~/"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Cleaning Docker system..."
            docker system prune -a -f

            echo "Pulling latest image..."
            docker pull "${{ secrets.DOCKERHUB_USERNAME }}/auth:latest"

            echo "Deploying stack..."
            docker stack deploy -c ~/docker-stack.yml mystack --detach=true